// Generated by BUCKLESCRIPT VERSION 2.2.3, PLEASE EDIT WITH CARE
'use strict';

var ApolloLinks = require("reason-apollo/src/ApolloLinks.bs.js");
var ApolloClient = require("apollo-client");
var ApolloInMemoryCache = require("reason-apollo/src/ApolloInMemoryCache.bs.js");

var inMemoryCache = ApolloInMemoryCache.createInMemoryCache(/* Some */[(function (obj) {
          return obj.id;
        })], /* None */0, /* () */0);

var httpLink = ApolloLinks.createHttpLink("https://api.graph.cool/simple/v1/cjfzh78qe0m1f0160xcrosm5l", /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* () */0);

var instance = new ApolloClient.ApolloClient({
      link: httpLink,
      cache: inMemoryCache,
      ssrMode: undefined,
      ssrForceFetchDelay: undefined,
      connectToDevTools: undefined,
      queryDeduplication: undefined
    });

exports.inMemoryCache = inMemoryCache;
exports.httpLink = httpLink;
exports.instance = instance;
/* inMemoryCache Not a pure module */
