// Generated by BUCKLESCRIPT VERSION 2.2.3, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var Pervasives = require("bs-platform/lib/js/pervasives.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var Text$BsReactNative = require("bs-react-native/src/components/text.js");
var View$BsReactNative = require("bs-react-native/src/components/view.js");
var Style$BsReactNative = require("bs-react-native/src/style.js");

var wrapper = Style$BsReactNative.style(/* :: */[
      Style$BsReactNative.backgroundColor("#fff"),
      /* :: */[
        Style$BsReactNative.padding(/* Pt */Block.__(0, [10])),
        /* [] */0
      ]
    ]);

var Styles = /* module */[/* wrapper */wrapper];

function formatPrice(price) {
  return Pervasives.string_of_float(price / 100);
}

var component = ReasonReact.statelessComponent("ProductItem");

function make(name, price, _) {
  var newrecord = component.slice();
  newrecord[/* render */9] = (function () {
      return ReasonReact.element(/* None */0, /* None */0, View$BsReactNative.make(/* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* Some */[wrapper], /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0)(/* array */[
                      ReasonReact.element(/* None */0, /* None */0, Text$BsReactNative.make(/* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* Some */[name], /* array */[])),
                      ReasonReact.element(/* None */0, /* None */0, Text$BsReactNative.make(/* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* Some */[formatPrice(price)], /* array */[]))
                    ]));
    });
  return newrecord;
}

exports.Styles = Styles;
exports.formatPrice = formatPrice;
exports.component = component;
exports.make = make;
/* wrapper Not a pure module */
