// Generated by BUCKLESCRIPT VERSION 2.2.3, PLEASE EDIT WITH CARE
'use strict';

var Home = require("./Home.bs.js");
var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");
var ProductAdd = require("./ProductAdd.bs.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");

var component = ReasonReact.reducerComponent("Router");

function make() {
  var newrecord = component.slice();
  newrecord[/* render */9] = (function (self) {
      var push = function (route, _) {
        return Curry._1(self[/* send */4], /* Push */[route]);
      };
      var match = self[/* state */2][/* route */0];
      if (match !== 0) {
        return ReasonReact.element(/* None */0, /* None */0, ProductAdd.make(push, /* array */[]));
      } else {
        return ReasonReact.element(/* None */0, /* None */0, Home.make(push, /* array */[]));
      }
    });
  newrecord[/* initialState */10] = (function () {
      return /* record */[/* route : Home */0];
    });
  newrecord[/* reducer */12] = (function (action, _) {
      return /* Update */Block.__(0, [/* record */[/* route */action[0]]]);
    });
  return newrecord;
}

exports.component = component;
exports.make = make;
/* component Not a pure module */
